export function selectBenefited(all: boolean = false): any {
  if (all)
    return {
      id: true,
      name: true,
      lastname: true,
      cellphone: true,
      birthday: true,
      civil: true,
      doc_type: true,
      health: true,
      poverty_level: true,
      housing_status: true,
      mode: true,
      sex: true,
      country: { select: { id: true, name: true } },
      department_birth: { select: { id: true, name: true } },
      department_live: { select: { id: true, name: true } },
      district_live: { select: { id: true, name: true } },
      education: { select: { id: true, name: true } },
      ethnic: { select: { id: true, name: true } },
      housing: { select: { id: true, name: true } },
      language_learned: { select: { id: true, name: true } },
      language_native: { select: { id: true, name: true } },
      province_birth: { select: { id: true, name: true } },
      province_live: { select: { id: true, name: true } },
    };
  return {
    id: true,
    doc_num: true,
    name: true,
    lastname: true,
    children: true,
    address: true,
    cellphone: true,
    telephone: true,
    assessment_cognitive: true,
    assessment_emotional: true,
    assessment_functional: true,
    assessment_sociofamily: true,
    read_write: true,
    profession: true,
    housing_onservation: true,
    state_services: true,
    pension_65: true,
    onp: true,
    police_pension: true,
    other_pension: true,
    sisfoh: true,
    works: true,
    occupation_type: true,
    occupation_other: true,
    monthly_income: true,
    other_income: true,
    income_source: true,
    income_amount: true,
    health_problem: true,
    health_condition: true,
    treatment: true,
    conadis: true,
    disability_vision: true,
    disability_hearing: true,
    disability_walking: true,
    disability_memory: true,
    disability_selfcare: true,
    disability_communication: true,
    violence_by: true,
    violence_type: true,
    abused: true,
    abuse_type: true,
    registration_reason: true,
    registration_reason_old: true,
    expected_services: true,
    birthday: true,
    registered_at: true,
    enrollmented_at: true,
    created_at: true,
    updated_at: true,
    deleted_at: true,
    civil: true,
    doc_type: true,
    health: true,
    poverty_level: true,
    housing_status: true,
    mode: true,
    sex: true,
    country: { select: { id: true, name: true } },
    department_birth: { select: { id: true, name: true } },
    department_live: { select: { id: true, name: true } },
    district_live: { select: { id: true, name: true } },
    education: { select: { id: true, name: true } },
    ethnic: { select: { id: true, name: true } },
    housing: { select: { id: true, name: true } },
    language_learned: { select: { id: true, name: true } },
    language_native: { select: { id: true, name: true } },
    province_birth: { select: { id: true, name: true } },
    province_live: { select: { id: true, name: true } },
  };
}
